### ISSUE TITLE
Citation for the paper

### ISSUE THREAD

**Issue by dqj5182** [arpita8/Awesome-Mixture-of-Experts-Papers#1]
May I ask how to cite your paper "THE EVOLUTION OF MIXTURE OF EXPERTS: A SURVEY FROM BASICS TO BREAKTHROUGHS"? Currently it seems that the paper is not present in Arxiv but only in researchgate. Could you provide bibtex for referencing your paper?

**Comment by arpita8** [comment]
Yes , you can use the research gate bibtex for referencing the paper. Let
me know if you have any other questions.

Thanks

Arpita Vats
